[package]
name = "usb-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
falcon-rust = { path = "../falcon-rust" }